config/routes.rb
IntellaShip::Application.routes.draw do

  namespace :admin do  namespace :system do resources :webex_service_types end end

  devise_for :users

  root :to => 'welcome#index'

  resource :welcome, :only => [:index]

  namespace :admin do
    namespace :system do
      resources :domains
    end
  end

end

app/models/admin/system.rb
module Admin::System
  def self.table_name_prefix
    'admin_system_'
  end
end

app/models/admin/system/domain.rb
class Admin::System::Domain < ActiveRecord::Base
  belongs_to :webex_service_type, :class_name => 'Admin::System::WebexServiceType'


end

app/models/admin/system/webex_service_type.rb
class Admin::System::WebexServiceType < ActiveRecord::Base

  has_many :domains, :class_name => 'Admin::System::Domain'

  MEETING     = 'Meeting Center'
  TRAINING   = 'Training Center'
  MEETING_ENTERPRISE     = 'Enterprise Edition Meeting Center'
  TRAINING_ENTERPRISE  = 'Enterprise Edition Training Center'

  NAMES = [MEETING,
           TRAINING,
           MEETING_ENTERPRISE,
           TRAINING_ENTERPRISE]

  # method to get all the service_types for a form
  # [['NY New York', 32], ['CA California', 3] ... ]
  #
  # @param [none]
  # @return [ Array[Array] ]
  def self.form_selector
    find(:all, :order => 'name ASC').collect { |record| [record.name, record.id] }
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :trackable,
         :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/admin/system/domains_controller.rb
class Admin::System::DomainsController < InheritedResources::Base
  before_filter :form_info

  private

  def form_info
    @service_types = Admin::System::WebexServiceType.form_selector
  end
end

app/controllers/admin/system/webex_service_types_controller.rb
class Admin::System::WebexServiceTypesController < InheritedResources::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'welcome'
  # GET /welcomes
  # GET /welcomes.json
  def index

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @welcomes }
    end
  end

end

app/helpers/admin/system/domains_helper.rb
module Admin::System::DomainsHelper
end

app/helpers/admin/system/webex_service_types_helper.rb
module Admin::System::WebexServiceTypesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/system/domains/_form.html.erb
<%= form_for(@domain) do |f| %>
  <% if @domain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@domain.errors.count, "error") %> prohibited this admin_system_domain from being saved:</h2>

      <ul>
      <% @domain.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @domain.new_record? %>
  <div class="field">
    <%= f.label :name, 'System Domain Name:' %><br />
    <%= f.text_field :name %>
  </div>
  <% end %>

  <div class="field">
    <%= f.check_box :enable %>
    <%= f.label :enable, 'Enable WebEx activities' %><br />
  </div>
  <div class="field">
    <%= f.label :server_name, 'Server Name:*' %><br />
    <%= f.text_field :server_name %>
  </div>
  <div class="field">
    <%= f.label :host_name, 'Host Name:*' %><br />
    <%= f.text_field :host_name %>
  </div>
  <div class="field">
    <%= f.label :site_id, 'Site ID:*' %><br />
    <%= f.text_field :site_id %>
  </div>
  <div class="field">
    <%= f.label :partner_id, 'Partner ID:*' %><br />
    <%= f.text_field :partner_id %>
  </div>
  <div class="field">
    <%= f.label :username, 'WebEx Administrator Username:*' %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password, 'WebEx Administrator Password:*' %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :meeting_password, 'Meeting or Training Center Password:*' %><br />
    <%= f.password_field :meeting_password %>
  </div>
  <div class="field">
    <%= f.label :webex_service_type, 'WebEx Service Type:*' %><br />
    <%= f.select :webex_service_type_id, @service_types %>
  </div>
  <div class="field">
    <%= f.check_box :use_credential%>
    <%= f.label :use_credential, 'Use existing WebEx credentials to launch WebEx sessions '  %><br />
  </div>
  <div class="field">
    <%= f.check_box :without_registration_password %>
    <%= f.label :without_registration_password, 'Allow participants without registration password to attend session'  %><br />
  </div>
  <div class="field">
    <%= f.check_box :without_session_password %>
    <%= f.label :without_session_password,'Allow participants without session password to attend session' %><br />
  </div>
  <div class="actions">
    <%= f.submit('Update Settings') %>
  </div>
<% end %>

app/views/admin/system/domains/edit.html.erb
<h1><%= "#{@domain.name} Settings" %></h1>
<h3><%= "Configure #{@domain.name} settings." %></h3>

<%= render 'form' %>

<%= link_to 'Back', admin_system_domains_path %>

app/views/admin/system/domains/index.html.erb
<h1>System Domain Settings</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Server name</th>
    <th></th>
    <th></th>
  </tr>

<% @domains.each do |admin_system_domain| %>
  <tr>
    <td><%= "#{admin_system_domain.name} Settings" %></td>
    <td><%= admin_system_domain.server_name %></td>
    <td><%= link_to 'Edit', edit_admin_system_domain_path(admin_system_domain) %></td>
    <td><%= link_to 'Destroy', admin_system_domain, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<% # link_to 'New Domain', new_admin_system_domain_path %>

app/views/admin/system/domains/new.html.erb
<h1>New admin_system_domain</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_system_domains_path %>

app/views/admin/system/domains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @domain.name %>
</p>

<p>
  <b>Enable:</b>
  <%= @domain.enable %>
</p>

<p>
  <b>Server name:</b>
  <%= @domain.server_name %>
</p>

<p>
  <b>Host name:</b>
  <%= @domain.host_name %>
</p>

<p>
  <b>Site:</b>
  <%= @domain.site_id %>
</p>

<p>
  <b>Partner:</b>
  <%= @domain.partner_id %>
</p>

<p>
  <b>Username:</b>
  <%= @domain.username %>
</p>

<p>
  <b>Password:</b>
  <%= @domain.password %>
</p>

<p>
  <b>Webex service type:</b>
  <%= @domain.webex_service_type %>
</p>

<p>
  <b>Use credential:</b>
  <%= @domain.use_credential %>
</p>

<p>
  <b>Allow registration passwords:</b>
  <%= @domain.allow_registration_passwords %>
</p>

<p>
  <b>Allow session password:</b>
  <%= @domain.allow_session_password %>
</p>


<%= link_to 'Edit', edit_admin_system_domain_path(@domain) %> |
<%= link_to 'Back', admin_system_domains_path %>

app/views/admin/system/webex_service_types/_form.html.erb
<%= form_for(@admin_system_webex_service_type) do |f| %>
  <% if @admin_system_webex_service_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_system_webex_service_type.errors.count, "error") %> prohibited this admin_system_webex_service_type from being saved:</h2>

      <ul>
      <% @admin_system_webex_service_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/system/webex_service_types/edit.html.erb
<h1>Editing admin_system_webex_service_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_system_webex_service_type %> |
<%= link_to 'Back', admin_system_webex_service_types_path %>

app/views/admin/system/webex_service_types/index.html.erb
<h1>Listing admin_system_webex_service_types</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_system_webex_service_types.each do |admin_system_webex_service_type| %>
  <tr>
    <td><%= admin_system_webex_service_type.name %></td>
    <td><%= link_to 'Show', admin_system_webex_service_type %></td>
    <td><%= link_to 'Edit', edit_admin_system_webex_service_type_path(admin_system_webex_service_type) %></td>
    <td><%= link_to 'Destroy', admin_system_webex_service_type, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Webex service type', new_admin_system_webex_service_type_path %>

app/views/admin/system/webex_service_types/new.html.erb
<h1>New admin_system_webex_service_type</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_system_webex_service_types_path %>

app/views/admin/system/webex_service_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @admin_system_webex_service_type.name %>
</p>


<%= link_to 'Edit', edit_admin_system_webex_service_type_path(@admin_system_webex_service_type) %> |
<%= link_to 'Back', admin_system_webex_service_types_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IntellaShip</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id='body_wrapper'>
  <div class="bp">
    <%= raw "<p class='flash_notice'> #{notice}</p>" if notice %>
    <%= raw "<p class='flash_error'>#{alert}</p>" if alert %>
  </div>

  <%= render 'shared/main_header' %>

  <div id='content_wrapper' class='container'>
    <%= yield %>
  </div>

</div>

<div id="footer_buffer" class='bp'>
  &nbsp;
</div>

<%= render 'shared/main_footer' %>

<%= yield :bottom %>

<script>
    jQuery(window).ready(
            function() {
                jQuery('.flash_notice').delay(6000).slideUp('slow');
                jQuery('.flash_error').delay(6000).slideUp('slow');
            }
    );
</script>

</body>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IntellaShip</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id='body_wrapper'>
  <div class="bp">
    <%= raw "<p class='flash_notice'> #{notice}</p>" if notice %>
    <%= raw "<p class='flash_error'>#{alert}</p>" if alert %>
  </div>

  <%= render 'shared/main_header' %>

  <div id='content_wrapper' class='container'>
    <%= yield %>
  </div>

</div>

<div id="footer_buffer" class='bp'>
  &nbsp;
</div>

<%= render 'shared/main_footer' %>

<%= yield :bottom %>

<script>
    jQuery(window).ready(
            function() {
                jQuery('.flash_notice').delay(6000).slideUp('slow');
                jQuery('.flash_error').delay(6000).slideUp('slow');
            }
    );
</script>

</body>
</html>

app/views/shared/_main_footer.html.erb
<%
loop_footer_tabs = {
  #'Terms & Conditions'  => terms_path,
  #'About'               => about_path#,
  #'Customer Service'    => faq_customer_service_path
}
%>

<div id="footer_wrapper" class='bp'>
  <div class="container" id="footer">
    <ul id='main-footer-tabs'>
      <% loop_footer_tabs.each_pair do |tab_name, tab_path| %>
        <li> <%= link_to_unless_current tab_name, tab_path %> </li> <%= '|' unless tab_name == 'About' %>
      <% end %>
    </ul>
  </div>
</div>
<div>

powered by <%= link_to image_tag('logo.gif'), 'http://www.intelladon.com/'%>
</div>

app/views/shared/_main_header.html.erb
<div id="header_wrapper" class='bp'>
  <div class="container logged-in" id="header">
    <ul id="menu-main">
      <li class="" id="menu-main-user">
        <div>
          <% if user_signed_in? %>
              <strong>Hi <%= current_user.try(:email) %></strong>
              <span>(<%= link_to translate(:not_you), destroy_user_session_path, method: :delete  %>)</span>
          <% else %>
              <strong><%= link_to translate(:sign_in), new_user_session_path %></strong> or
              <span><%= link_to translate(:sign_up), new_user_registration_path %></span>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/welcome/index.html.erb
<br/>
<table>

  <tr>
    <td><%= image_tag 'travel_port.png' %></td>
    <td><%= link_to image_tag('admin.png', :title => t(:link_admin_title)), admin_system_domains_path %></td>
  </tr>
</table>